let names = {
    "firstpart": [
        { "name": "Lucky" },
        { "name": "Sunny" },
        { "name": "Jolly" },
        { "name": "Gentle" },
        { "name": "Graceful" },
        { "name": "Witty" },
        { "name": "Radiant" },
        { "name": "Cheerful" },
        { "name": "Gentle" },
        { "name": "Lively" },
        { "name": "Zealous" },
        { "name": "Daring" },
        { "name": "Dynamic" },
        { "name": "Majestic" },
        { "name": "Quirky" },
        { "name": "Dazzling" },
        { "name": "Serene" },
        { "name": "Adventurous" },
        { "name": "Whimsical" },
        { "name": "Vibrant" },
        { "name": "Eloquent" },
        { "name": "Glamorous" },
        { "name": "Enchanting" },
        { "name": "Sparkling" },
        { "name": "Jubilant" },
        { "name": "Dynamic" },
        { "name": "Thrilling" },
        { "name": "Zesty" },
        { "name": "Epic" },
        { "name": "Ambitious" },
        { "name": "Charming" },
        { "name": "Spirited" },
        { "name": "Harmonious" },
        { "name": "Playful" },
        { "name": "Creative" },
        { "name": "Inquisitive" },
        { "name": "Dazzling" },
        { "name": "Energetic" },
        { "name": "Magical" },
        { "name": "Fantastic" },
        { "name": "Wholesome" },
        { "name": "Zenith" },
        { "name": "Funny" },
        { "name": "Clever" },
        { "name": "Happy" },
        { "name": "BigBlack" },
        { "name": "Beautiful" },
        { "name": "Smart" },
        { "name": "Bombastic" },
        { "name": "Cute" },
        { "name": "Kind" },
        { "name": "Brave" },
        { "name": "Exploded" },
        {"name": "Rizzy"},
        {"name": "Beta"},
        {"name": "Gay"},
        {"name": "Sigma"},
        {"name": "Touching"},
        {"name": "Bony"},
        {"name": "Kebap"},
        {"name": "Ben"},
    ],
    "secondpart": [
        {"name": "Gyat"},
        {"name": "Rizzler"},
        { "name": "Niqer" },
        { "name": "Whiskers" },
        { "name": "Sunshine" },
        { "name": "Mewer" },
        { "name": "Meadow" },
        { "name": "Breezey" },
        { "name": "Harmony" },
        { "name": "Sunset" },
        { "name": "Grove" },
        { "name": "Mischief" },
        { "name": "Petal" },
        { "name": "Zephyr" },
        { "name": "Glimmer" },
        { "name": "Aurora" },
        { "name": "Frost" },
        { "name": "Cascade" },
        { "name": "Whisper" },
        { "name": "Lagoon" },
        { "name": "Pebble" },
        { "name": "Wanderer" },
        { "name": "Majesty" },
        { "name": "Zest" },
        { "name": "Harmony" },
        { "name": "Quest" },
        { "name": "Lullaby" },
        { "name": "Serenade" },
        { "name": "Tranquil" },
        { "name": "Velvet" },
        { "name": "Crescent" },
        { "name": "Cascade" },
        { "name": "Eclipse" },
        { "name": "Radiance" },
        { "name": "Journey" },
        { "name": "Velvet" },
        { "name": "Oasis" },
        { "name": "Sapphire" },
        { "name": "Blossom" },
        { "name": "Lush" },
        { "name": "Pebble" },
        { "name": "Bliss" },
        { "name": "Mystique" },
        { "name": "Glider" },
        { "name": "Aura" },
        { "name": "Sculptor" },
        { "name": "Doggy" },
        { "name": "Carsten" },
        { "name": "Housely" },
        { "name": "Arabicus" },
        { "name": "Mountainy" },
        { "name": "Treester" },
        { "name": "Riversus" },
        { "name": "Bookly" },
        { "name": "Timus" },
        { "name": "Christianus" },
        { "name": "Steffanus" },
        { "name": "Manettyl" },
        { "name": "Pabsti" },
        { "name": "Wonka" },
        { "name": "Abdudli" },
        { "name": "Baumaxl"},
        {"name": "Rufus"},
        {"name": "Kids"},
        {"name": "Man"},
        {"name": "Thomas"},
        {"name": "Kerim"},
        {"name": "Dover"},
    ]
};